{"uuid": "fb65f5af-4ab7-4a7e-9e8c-c067d3929cc0", "children": ["1d70267f-2981-4b98-b61c-d60c1f058f6c"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=129.0.6668.90)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6C38E9412+29090]\n\t(No symbol) [0x00007FF6C385E239]\n\t(No symbol) [0x00007FF6C371B1DA]\n\t(No symbol) [0x00007FF6C36EFAF5]\n\t(No symbol) [0x00007FF6C379E2C7]\n\t(No symbol) [0x00007FF6C37B5EB1]\n\t(No symbol) [0x00007FF6C3796493]\n\t(No symbol) [0x00007FF6C37609D1]\n\t(No symbol) [0x00007FF6C3761B31]\n\tGetHandleVerifier [0x00007FF6C3C0871D+3302573]\n\tGetHandleVerifier [0x00007FF6C3C54243+3612627]\n\tGetHandleVerifier [0x00007FF6C3C4A417+3572135]\n\tGetHandleVerifier [0x00007FF6C39A5EB6+801862]\n\t(No symbol) [0x00007FF6C386945F]\n\t(No symbol) [0x00007FF6C3864FB4]\n\t(No symbol) [0x00007FF6C3865140]\n\t(No symbol) [0x00007FF6C385461F]\n\tBaseThreadInitThunk [0x00007FF9A51C257D+29]\n\tRtlUserThreadStart [0x00007FF9A6B8AF08+40]\n\n", "trace": "  File \"D:\\Python\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\Python\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Python\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Python\\Lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\Credence Projects\\BankApp_Pytest\\BankApp_Pytest\\testcases\\conftest.py\", line 24, in setup\n    driver.maximize_window()\n  File \"D:\\Python\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 506, in maximize_window\n    self.execute(command, None)\n  File \"D:\\Python\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Python\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1728714670623, "stop": 1728714675163}], "start": 1728714670623, "stop": 1728714675283}